#!/bin/sh

sudo pacman -Syu --noconfirm

pacman_packages=(
    alsa-utils
    bat
    blueman
    bluez-utils
    brightnessctl
    cliphist
    docker
    docker-compose
    eza
    git
    git-delta
    htop
    hypridle
    hyprland
    hyprlock
    hyprpaper
    libreoffice-still
    ly
    otf-codenewroman-nerd
    pamixer
    pavucontrol
    perl-image-exiftool
    pulseaudio
    pulseaudio-alsa
    pulseaudio-bluetooth
    python-pywal16
    ripgrep
    rust
    ttf-hack-nerd
    ttf-nerd-fonts-symbols
    udiskie
    unzip
    usbutils
    waybar
    wget
    wlogout
    wofi
    zip
)

aur_packages=(
    visual-studio-code-bin
    librewolf-bin
    )

sudo pacman -S --noconfirm "${pacman_packages[@]}"

cd /tmp || exit

git clone https://aur.archlinux.org/yay.git

cd yay || exit
makepkg -si --noconfirm

cd ..
rm -rf yay

yay -S --noconfirm "${aur_packages[@]}"
